import type { Metadata } from "next";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function FrontendLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <section>
        <Header />
        <div className="mx-auto max-w-5xl w-full">{children}</div>
      </section>
    </ClerkProvider>
  );
}