import type { Metadata } from "next";
import Header from "@/components/header";
import { SanityLive } from "@/sanity/lib/live";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function FrontendLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      <Header />
      <div className="mx-auto max-w-2xl px-4 w-full">
        {children}
        <SanityLive />
      </div>
    </section>
  );
}